# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
pipelines:
  default:
    - parallel:
      - step:
          image: python:2.7.15
          name: Build and test Python2
          caches:
            - pip
          script:
            - pip install -r requirements.txt
            - pip install -r test_requirements.txt
            - mkdir -p test-results
            - nosetests --with-xunit --xunit-file=test-results/py2_combined_results.xml --with-coverage --cover-erase --cover-xml --cover-xml-file=test-results/py2_coverage.xml  --cover-package=astair tests/*
      - step:
          image: python:3.5.6
          name: Build and test Python3
          caches:
            - pip3
          script:
            - pip3 --cache-dir ~/.cache/pip3 install -r requirements.txt
            - pip3 --cache-dir ~/.cache/pip3 install -r test_requirements.txt
            - mkdir -p test-results
            - nosetests --with-xunit --xunit-file=test-results/py3_combined_results.xml --with-coverage --cover-erase --cover-xml --cover-xml-file=test-results/py3_coverage.xml  --cover-package=astair tests/*

definitions:
  caches:
    pip3: ~/.cache/pip3
